### PR TITLE
Add support for Linux x86_64

### PR DESCRIPTION
**Pull request by michaelklishin**

### CODE REVIEW

**Comment by hoebat** [comment]
thanks michael! 

I'm assuming that you need to update sigar as well?

**Comment by michaelklishin** [comment]
How do you mean?

**Comment by hoebat** [comment]
Do you need to increment the version or anything to be able to use it through clojars?

**Comment by michaelklishin** [comment]
Well, yes, I pushed it in my own artefact group. I will bump the version.

**Comment by hoebat** [comment]
If you like, I'll can give you commit access to sigar if you need to do more changes. I'm a bit busy at the moment and quite rusty with this lib.

**Comment by michaelklishin** [comment]
@zcaudate ok, sounds good.

**Comment by hoebat** [comment]
Okay.

You can now push to clojars too for sigmund and sigar groups

**Pull request merged**
